// Mocks generated by Mockito 5.0.16 from annotations
// in hamsa_lomi/test/data/auth/repositories/auth_repository_impl_test.dart.
// Do not manually edit this file.

// Dart imports:
import 'dart:async' as _i4;

// Package imports:
import 'package:firebase_auth/firebase_auth.dart' as _i5;
import 'package:mockito/mockito.dart' as _i1;

// Project imports:
import 'package:hamsa_lomi/data/auth/data_sources/auth_data_source.dart' as _i3;
import 'package:hamsa_lomi/data/auth/models/create_user_model.dart' as _i6;
import 'package:hamsa_lomi/domain/auth/entities/create_user.dart' as _i2;

import 'package:hamsa_lomi/domain/auth/entities/verify_phone_number_param.dart'
    as _i7;
import 'package:hamsa_lomi/domain/auth/entities/verify_sms_code_param.dart'
    as _i8;

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

class _FakeCreateUser_0 extends _i1.Fake implements _i2.CreateUser {}

/// A class which mocks [AuthDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthDataSource extends _i1.Mock implements _i3.AuthDataSource {
  MockAuthDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Stream<_i5.User?> get userChanges =>
      (super.noSuchMethod(Invocation.getter(#userChanges),
          returnValue: Stream<_i5.User?>.empty()) as _i4.Stream<_i5.User?>);
  @override
  _i4.Future<_i2.CreateUser> createAccount(_i6.CreateUserModel? userModel) =>
      (super.noSuchMethod(Invocation.method(#createAccount, [userModel]),
              returnValue: Future<_i2.CreateUser>.value(_FakeCreateUser_0()))
          as _i4.Future<_i2.CreateUser>);
  @override
  _i4.Future<void> signInWithEmail(String? email, String? password) => (super
      .noSuchMethod(Invocation.method(#signInWithEmail, [email, password]),
          returnValue: Future<void>.value(),
          returnValueForMissingStub: Future<void>.value()) as _i4.Future<void>);
  @override
  _i4.Future<void> signInWithPhone(_i7.VerifyPhoneNumberParam? param) =>
      (super.noSuchMethod(Invocation.method(#signInWithPhone, [param]),
          returnValue: Future<void>.value(),
          returnValueForMissingStub: Future<void>.value()) as _i4.Future<void>);
  @override
  _i4.Future<void> verifySmsCode(_i8.VerifySmsCodeParam? param) =>
      (super.noSuchMethod(Invocation.method(#verifySmsCode, [param]),
          returnValue: Future<void>.value(),
          returnValueForMissingStub: Future<void>.value()) as _i4.Future<void>);
  @override
  String toString() => super.toString();
}
