// Mocks generated by Mockito 5.0.16 from annotations
// in hamsa_lomi/test/domain/auth/use_cases/create_account_use_case_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i4;

import 'package:dartz/dartz.dart' as _i2;
import 'package:firebase_auth/firebase_auth.dart' as _i5;
import 'package:hamsa_lomi/domain/auth/entities/create_user.dart' as _i7;
import 'package:hamsa_lomi/domain/auth/entities/sign_in_credential.dart' as _i8;
import 'package:hamsa_lomi/domain/auth/entities/verify_phone_number_param.dart'
    as _i9;
import 'package:hamsa_lomi/domain/auth/entities/verify_sms_code_param.dart'
    as _i10;
import 'package:hamsa_lomi/domain/auth/repositories/auth_repository.dart'
    as _i3;
import 'package:hamsa_lomi/domain/core/failure.dart' as _i6;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

class _FakeEither_0<L, R> extends _i1.Fake implements _i2.Either<L, R> {}

/// A class which mocks [AuthRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthRepository extends _i1.Mock implements _i3.AuthRepository {
  MockAuthRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Stream<_i5.User?> get userChanges =>
      (super.noSuchMethod(Invocation.getter(#userChanges),
          returnValue: Stream<_i5.User?>.empty()) as _i4.Stream<_i5.User?>);
  @override
  _i4.Future<_i2.Either<_i6.Failure, _i7.CreateUser>> createAccount(
          _i7.CreateUser? user) =>
      (super.noSuchMethod(Invocation.method(#createAccount, [user]),
          returnValue: Future<_i2.Either<_i6.Failure, _i7.CreateUser>>.value(
              _FakeEither_0<_i6.Failure, _i7.CreateUser>())) as _i4
          .Future<_i2.Either<_i6.Failure, _i7.CreateUser>>);
  @override
  _i4.Future<_i2.Either<_i6.Failure, _i2.Unit>> signInWithEmail(
          _i8.SignInCredential? credential) =>
      (super.noSuchMethod(Invocation.method(#signInWithEmail, [credential]),
              returnValue: Future<_i2.Either<_i6.Failure, _i2.Unit>>.value(
                  _FakeEither_0<_i6.Failure, _i2.Unit>()))
          as _i4.Future<_i2.Either<_i6.Failure, _i2.Unit>>);
  @override
  _i4.Future<_i2.Either<_i6.Failure, _i2.Unit>> signInWithPhone(
          _i9.VerifyPhoneNumberParam? param) =>
      (super.noSuchMethod(Invocation.method(#signInWithPhone, [param]),
              returnValue: Future<_i2.Either<_i6.Failure, _i2.Unit>>.value(
                  _FakeEither_0<_i6.Failure, _i2.Unit>()))
          as _i4.Future<_i2.Either<_i6.Failure, _i2.Unit>>);
  @override
  _i4.Future<_i2.Either<_i6.Failure, _i2.Unit>> verifySmsCode(
          _i10.VerifySmsCodeParam? param) =>
      (super.noSuchMethod(Invocation.method(#verifySmsCode, [param]),
              returnValue: Future<_i2.Either<_i6.Failure, _i2.Unit>>.value(
                  _FakeEither_0<_i6.Failure, _i2.Unit>()))
          as _i4.Future<_i2.Either<_i6.Failure, _i2.Unit>>);
  @override
  String toString() => super.toString();
}
