include: package:effective_dart/analysis_options.yaml

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "**/*.mocks.dart"
    - "**/*.config.dart"
  errors:
    # treat missing required parameters as a warning (not a hint)
    missing_required_param: warning
    # treat missing returns as a warning (not a hint)
    missing_return: warning

linter:
  rules:
    public_member_api_docs: false
    prefer_single_quotes: true
    one_member_abstracts: false
    avoid_print: true
    sort_pub_dependencies: true
    directives_ordering: false

