name: hamsa_lomi
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  cloud_firestore: ^3.1.0
  cupertino_icons: ^1.0.2
  dartz: ^0.10.0-nullsafety.2
  datetime_picker_formfield: ^2.0.0
  effective_dart: ^1.3.2
  equatable: ^2.0.3
  file_picker: ^4.3.1
  firebase_auth: ^3.1.0
  firebase_core: ^1.6.0
  firebase_storage: ^10.2.4
  flutter:
    sdk: flutter
  flutter_bloc: ^7.3.0
  flutter_svg: ^0.22.0
  formz: ^0.4.0
  get_it: null
  image_cropper: ^1.4.1
  image_picker: ^0.8.4+4
  import_sorter: ^4.6.0
  injectable: ^1.4.1
  intl: ^0.17.0
  intl_phone_field: ^2.0.1
  json_annotation: ^4.4.0
  mockito: ^5.0.10
  sms_autofill: ^2.0.1

dev_dependencies:
  build_runner: ^2.0.5
  flutter_test:
    sdk: flutter
  injectable_generator: ^1.4.1
  json_serializable: ^6.1.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - lib/presentation/assets/images/rectangle_background.png
    - lib/presentation/assets/icons/balance_icon.svg
    - lib/presentation/assets/icons/charity.svg
    - lib/presentation/assets/icons/education.svg
    - lib/presentation/assets/icons/health.svg
    - lib/presentation/assets/icons/options.svg
    - lib/presentation/assets/icons/payment_icon.svg
    - lib/presentation/assets/icons/edit_icon.svg
    - lib/presentation/assets/images/rectangle_background.png
    - lib/presentation/assets/icons/hamsa_logo.svg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Poppins
      fonts:
        - asset: lib/presentation/assets/fonts/Poppins/Poppins-Regular.ttf
        - asset: lib/presentation/assets/fonts/Poppins/Poppins-Bold.ttf
        - asset: lib/presentation/assets/fonts/Poppins/Poppins-Italic.ttf
          style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
